[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]  # <--- WICHTIG: Dies sagt, dass die Version dynamisch ist
name = "mpylab"
requires-python = ">=3.11"
authors = [
    {name = "Hans Georg Krauthäuser", email = "hgk@ieee.org"},
    {name = "Christian Albrecht"},
    {name = "Stephan"},
    {name = "Oscar Rivera"},
    {name = "Mathias Magdowski"},
    {name = "Sophie Rautschek"},
    {name = "Frank Schröder"},
    {name = "Luzia Tesar"},
    {name = "Konstantin Pasche"},
    {name = "Thomas Reidemeister"}
]
maintainers = [
  {name = "Hans Georg Krauthäuser", email = "hgk@ieee.org"}
]
description = "A framework to simplify development of measurement 'scripts' for measurements in laboratories over e.g pyvisa."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["pyvisa", "gpib", "measurements", "laboratory"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    #"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Topic :: Scientific/Engineering",
    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
dependencies = [
    "bidict>=0.23.1",
    "gpib-ctypes>=0.3.0",
    "ipywidgets>=8.1.8",
    "levenshtein>=0.27.1",
    "matplotlib>=3.7.5",
    #"msvcrt; sys_platform == 'win32'",
    "numpy>=1.24.4",
    "pathvalidate>=3.3.1",
    "plotly>=6.5.2",
    "ply>=3.11",
    "psutil>=7.2.2",
    "pydot>=4.0.1",
    "pyparsing>=3.1.4",
    "pyserial>=3.5",
    "pyside6>=6.9.2",
    "pyusb>=1.2.1",
    "pyvisa>=1.14.1",
    "pyvisa-py>=0.7.2",
    "requests>=2.32.5",
    "scipy>=1.10.1",
    "scipy-stubs~=1.16.1",
    "scuq>=0.9",
    "simpleeval>=0.9.13",
    "sphinx>=9.0.4",
    "yapps2>=2.2.0",
    "zeroconf>=0.148.0",
]

# Optional: Extrainstallation (z.B. für Docs)
[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black",
    "flake8",
]
docs = [
    "sphinx>=8.0",
    "sphinx-rtd-theme",
    "breathe",
]
gui = ["PySide6"]


[project.urls]
Homepage = "https://www.tu-dresden.de/et/tet"
Repository = "https://gitlab.hrz.tu-chemnitz.de/chair-of-electromagnetic-theory-and-compatibility-at-tu-dresden/mpylab/mpylab.git"
Documentation = "https://mpylab-75fcff.gp.hrz.tu-chemnitz.de/"

[tool.setuptools.packages.find]
where = ["src"]  # Wenn dein Code im 'src' Ordner liegt
# Falls dein Code im Root liegt, ändere dies zu: where = ["."]

[tool.setuptools_scm]
# Konfiguration für die Versionsgenerierung
write_to = "src/mpylab/_version.py"  # Erstellt eine Datei mit der Version im Code
write_to_template = '__version__ = "{version}"\n'
# Fallback Version, falls kein Tag existiert (nur für lokale Entwicklung)
fallback_version = "0.0.0.dev0"
