
# plyparser_DatFile_parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\x98\x10m\xfe\xbb\x99\xe5\xa1\xd7$\xc6\x06\x82j\xe8\x1d'

_lr_action_items = {'LBRACE':([1,2,10,11,12,21,36,37,],[9,9,9,-13,-12,9,-14,-15,]),'RBRACE':([33,],[36,]),'FPNUMBER':([0,1,2,3,5,7,9,10,11,12,13,21,22,24,25,26,28,29,31,32,34,36,37,],[1,11,11,-3,15,1,20,11,-13,-12,23,11,-11,-9,-8,-4,-5,33,35,-6,-10,-14,-15,]),'ABSERROR':([0,3,7,22,24,25,26,28,32,34,],[2,-3,2,-11,-9,-8,-4,-5,-6,-10,]),'NEWLINE':([0,3,7,10,11,12,14,15,16,17,19,22,24,25,26,27,28,30,32,34,36,37,],[3,-3,3,22,-13,-12,24,25,26,-7,28,-11,-9,-8,-4,32,-5,34,-6,-10,-14,-15,]),'RELERROR':([0,3,7,22,24,25,26,28,32,34,],[5,-3,5,-11,-9,-8,-4,-5,-6,-10,]),'COMMA':([20,23,],[29,31,]),'RSBRACE':([35,],[37,]),'FUNIT':([0,3,7,22,24,25,26,28,32,34,],[6,-3,6,-11,-9,-8,-4,-5,-6,-10,]),'$end':([3,4,7,18,22,24,25,26,28,32,34,],[-3,0,-2,-1,-11,-9,-8,-4,-5,-6,-10,]),'ID':([6,8,17,19,],[17,17,-7,17,]),'UNIT':([0,3,7,22,24,25,26,28,32,34,],[8,-3,8,-11,-9,-8,-4,-5,-6,-10,]),'LSBRACE':([1,2,10,11,12,21,36,37,],[13,13,13,-13,-12,13,-14,-15,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,7,],[7,7,]),'lines':([0,7,],[4,18,]),'number':([1,2,10,21,],[12,12,12,12,]),'val':([1,2,10,21,],[10,14,21,30,]),'idanycase':([6,8,19,],[16,19,27,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('lines',2,'p_lines_line','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',131),
  ('lines',1,'p_lines_line','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',132),
  ('line',1,'p_line_empty','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',137),
  ('line',3,'p_line_funit','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',141),
  ('line',3,'p_line_unit','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',146),
  ('line',4,'p_line_unit','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',147),
  ('idanycase',1,'p_idanycase_id','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',155),
  ('line',3,'p_line_relerr','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',160),
  ('line',3,'p_line_abserr','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',165),
  ('line',5,'p_line_data1','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',170),
  ('line',3,'p_line_data2','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',176),
  ('val',1,'p_val_number','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',190),
  ('number',1,'p_number_fpnumber','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',194),
  ('val',5,'p_val_ri','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',199),
  ('val',5,'p_val_ma','/Users/hgkrauth/Documents/Mpy/mpy/tools/dataparser.py',205),
]
