import sys, re
from yapps import runtime
import ast

nodes = {}
graph = {}


def init_nodes_graph():
    nodes.clear()
    graph.clear()


def add_node(i, dr=None):
    if dr is None:
        dr = {}

    if i not in nodes:
        nodes[i] = dr.copy()
    else:
        nodes[i].update(dr)


def add_edge(left, right=None, attr=None):
    if right is None:
        right = []
    if attr is None:
        attr = {}

    add_node(left)
    for r in right:
        add_node(r)

    if left not in graph:
        graph[left] = {}

    for r in right:
        graph[left][r] = attr.copy()



# Begin -- grammar generated by Yapps

class DOTScanner(runtime.Scanner):
    patterns = [
        ("'@'", re.compile('@')),
        ("'\\\\)'", re.compile('\\)')),
        ("'\\\\('", re.compile('\\(')),
        ("':'", re.compile(':')),
        ("'--|->'", re.compile('--|->')),
        ("','", re.compile(',')),
        ("'\\\\]'", re.compile('\\]')),
        ("'\\\\['", re.compile('\\[')),
        ("'edge|EDGE'", re.compile('edge|EDGE')),
        ("'node|NODE'", re.compile('node|NODE')),
        ("'='", re.compile('=')),
        ("';'", re.compile(';')),
        ("'digraph|DIGRAPH'", re.compile('digraph|DIGRAPH')),
        ("'}'", re.compile('}')),
        ("'{'", re.compile('{')),
        ("'graph|GRAPH'", re.compile('graph|GRAPH')),
        ("'strict|STRICT'", re.compile('strict|STRICT')),
        ('\\s+', re.compile('\\s+')),
        ('#.*', re.compile('#.*')),
        ('//.*', re.compile('//.*')),
        ('NUM', re.compile('[0-9]+')),
        ('ID', re.compile('[_a-zA-Z][_a-zA-Z0-9]*')),
        ('STR', re.compile('"([^\\"]+|\\\\.)*"')),
        ('END', re.compile('$')),
    ]
    def __init__(self, str,*args,**kw):
        runtime.Scanner.__init__(self,None,{'\\s+':None,'#.*':None,'//.*':None,},str,*args,**kw)

class DOT(runtime.Parser):
    Context = runtime.Context
    def graph(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'graph', [])
        if self._peek("'strict|STRICT'", "'graph|GRAPH'", "'digraph|DIGRAPH'", context=_context) == "'strict|STRICT'":
            self._scan("'strict|STRICT'", context=_context)
        _token = self._peek("'graph|GRAPH'", "'digraph|DIGRAPH'", context=_context)
        if _token == "'graph|GRAPH'":
            self._scan("'graph|GRAPH'", context=_context)
            if self._peek("'{'", 'ID', 'STR', 'NUM', "','", "'\\\\)'", "'='", "'--|->'", "'\\\\['", "':'", "'@'", "';'", "'}'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", "'\\\\]'", context=_context) in ['ID', 'STR', 'NUM']:
                id = self.id(_context)
            self._scan("'{'", context=_context)
            init_nodes_graph()
            stmt_list = self.stmt_list(_context)
            self._scan("'}'", context=_context)
        else: # == "'digraph|DIGRAPH'"
            self._scan("'digraph|DIGRAPH'", context=_context)
            if self._peek("'{'", 'ID', 'STR', 'NUM', "','", "'\\\\)'", "'='", "'--|->'", "'\\\\['", "':'", "'@'", "';'", "'}'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", "'\\\\]'", context=_context) in ['ID', 'STR', 'NUM']:
                id = self.id(_context)
            self._scan("'{'", context=_context)
            init_nodes_graph()
            stmt_list = self.stmt_list(_context)
            self._scan("'}'", context=_context)
        END = self._scan('END', context=_context)
        return (nodes, graph)

    def stmt_list(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'stmt_list', [])
        while self._peek("'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) != "'}'":
            stmt = self.stmt(_context)
            if self._peek("';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) == "';'":
                self._scan("';'", context=_context)

    def stmt(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'stmt', [])
        _token = self._peek("'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context)
        if _token not in ["'{'", 'ID', 'STR', 'NUM']:
            attr_stmt = self.attr_stmt(_context)
        elif _token != "'{'":
            id = self.id(_context)
            i = id
            _token = self._peek("'='", "'--|->'", "'\\\\['", "':'", "'@'", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context)
            if _token == "'='":
                self._scan("'='", context=_context)
                id = self.id(_context)
                j = id
            elif _token in ["':'", "'@'"]:
                port = self.port(_context)
                _token = self._peek("'--|->'", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context)
                if _token == "'--|->'":
                    edgeRHS = self.edgeRHS(_context)
                    l = {}
                    if self._peek("'\\\\['", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) == "'\\\\['":
                        attr_list = self.attr_list(None, _context)
                        l = attr_list
                    add_edge(i, edgeRHS, l)
                else:
                    add_node(i)
            elif _token == "'--|->'":
                edgeRHS = self.edgeRHS(_context)
                l = {}
                if self._peek("'\\\\['", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) == "'\\\\['":
                    attr_list = self.attr_list(None, _context)
                    l = attr_list
                add_edge(i, edgeRHS, l)
            elif _token == "'\\\\['":
                attr_list = self.attr_list(None, _context)
                add_node(i, attr_list)
            else:
                add_node(i)
        else: # == "'{'"
            self._scan("'{'", context=_context)
            stmt_list = self.stmt_list(_context)
            self._scan("'}'", context=_context)

    def attr_stmt(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'attr_stmt', [])
        _token = self._peek("'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", context=_context)
        if _token == "'graph|GRAPH'":
            self._scan("'graph|GRAPH'", context=_context)
        elif _token == "'node|NODE'":
            self._scan("'node|NODE'", context=_context)
        else: # == "'edge|EDGE'"
            self._scan("'edge|EDGE'", context=_context)
        attr_list = self.attr_list(None, _context)
        return attr_list

    def attr_list(self, adir, _parent=None):
        _context = self.Context(_parent, self._scanner, 'attr_list', [adir])
        while 1:
            self._scan("'\\\\['", context=_context)
            if adir is None: adir = {}
            if self._peek("'\\\\]'", 'ID', 'STR', 'NUM', context=_context) != "'\\\\]'":
                a_list = self.a_list(adir, _context)
            self._scan("'\\\\]'", context=_context)
            if self._peek("'\\\\['", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) != "'\\\\['": break
        return adir

    def a_list(self, adir, _parent=None):
        _context = self.Context(_parent, self._scanner, 'a_list', [adir])
        while 1:
            id = self.id(_context)
            k = id
            if self._peek("'='", "','", 'ID', 'STR', 'NUM', "'\\\\]'", context=_context) == "'='":
                self._scan("'='", context=_context)
                id = self.id(_context)
                adir[k] = id
            if self._peek("','", 'ID', 'STR', 'NUM', "'\\\\]'", context=_context) == "','":
                self._scan("','", context=_context)
            if self._peek('ID', 'STR', 'NUM', "'\\\\]'", context=_context) not in ['ID', 'STR', 'NUM']: break
        return adir

    def edge_stmt(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'edge_stmt', [])
        node_id = self.node_id(_context)
        edgeRHS = self.edgeRHS(_context)
        if self._peek("'\\\\['", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) == "'\\\\['":
            attr_list = self.attr_list(None, _context)

    def edgeRHS(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'edgeRHS', [])
        while 1:
            list = []
            self._scan("'--|->'", context=_context)
            node_id = self.node_id(_context)
            list.append(node_id)
            if self._peek("'--|->'", "'\\\\['", "';'", "'}'", "'{'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", 'ID', 'STR', 'NUM', context=_context) != "'--|->'": break
        return list

    def node_stmt(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'node_stmt', [])
        node_id = self.node_id(_context)
        nodes[node_id] = {}
        if 1:
            attr_list = self.attr_list(None, _context)
            nodes[node_id] = attr_list
        return nodes

    def node_id(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'node_id', [])
        id = self.id(_context)
        if self._peek("':'", "'@'", "'--|->'", "','", "'\\\\)'", "'\\\\['", "'{'", "'='", "';'", 'ID', 'STR', 'NUM', "'}'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", "'\\\\]'", context=_context) in ["':'", "'@'"]:
            port = self.port(_context)
        return id

    def port(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'port', [])
        _token = self._peek("':'", "'@'", context=_context)
        if _token == "':'":
            port_location = self.port_location(_context)
            if self._peek("'@'", "','", "'\\\\)'", "':'", "'{'", "'='", "'--|->'", "'\\\\['", "';'", 'ID', 'STR', 'NUM', "'}'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", "'\\\\]'", context=_context) == "'@'":
                port_angle = self.port_angle(_context)
        else: # == "'@'"
            port_angle = self.port_angle(_context)
            if self._peek("':'", "'@'", "','", "'\\\\)'", "'{'", "'='", "'--|->'", "'\\\\['", "';'", 'ID', 'STR', 'NUM', "'}'", "'graph|GRAPH'", "'node|NODE'", "'edge|EDGE'", "'\\\\]'", context=_context) == "':'":
                port_location = self.port_location(_context)

    def port_location(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'port_location', [])
        self._scan("':'", context=_context)
        _token = self._peek("'\\\\('", 'ID', 'STR', 'NUM', context=_context)
        if _token != "'\\\\('":
            id = self.id(_context)
        else: # == "'\\\\('"
            self._scan("'\\\\('", context=_context)
            id = self.id(_context)
            self._scan("','", context=_context)
            id = self.id(_context)
            self._scan("'\\\\)'", context=_context)

    def port_angle(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'port_angle', [])
        self._scan("'@'", context=_context)
        id = self.id(_context)

    def id(self, _parent=None):
        _context = self.Context(_parent, self._scanner, 'id', [])
        _token = self._peek('ID', 'STR', 'NUM', context=_context)
        if _token == 'ID':
            ID = self._scan('ID', context=_context)
            return ID
        elif _token == 'STR':
            STR = self._scan('STR', context=_context)
            return ast.literal_eval(STR)
        else: # == 'NUM'
            NUM = self._scan('NUM', context=_context)
            return int(NUM)


def parse(rule, text):
    P = DOT(DOTScanner(text))
    return runtime.wrap_error_reporter(P, rule)

if __name__ == '__main__':
    from sys import argv, stdin
    if len(argv) >= 2:
        if len(argv) >= 3:
            f = open(argv[2],'r')
        else:
            f = stdin
        print(parse(argv[1], f.read()))
    else: print ('Args:  <rule> [<filename>]', file=sys.stderr)
# End -- grammar generated by Yapps
