#!/usr/bin/env python3
"""Generate a complete Sphinx automodule page for mpylab modules."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import re

EXCLUDE_MODULES = {
    # Generated by yapps2 from dot.g; documented in a dedicated grammar page.
    "mpylab.tools.dot",
}


def discover_modules(src_root: Path) -> list[str]:
    modules: list[str] = []
    for pyf in sorted(src_root.rglob("*.py")):
        if "__pycache__" in pyf.parts or pyf.name == "__init__.py":
            continue
        rel = pyf.relative_to(src_root).with_suffix("")
        parts = list(rel.parts)
        if not all(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", p) for p in parts):
            continue
        mod = ".".join(["mpylab"] + parts)
        if ".legacy." in mod:
            continue
        if mod in EXCLUDE_MODULES:
            continue
        modules.append(mod)
    return modules


def make_title(module: str) -> str:
    return f":mod:`{module}`"


def section_underline(title: str) -> str:
    return "-" * len(title)


def build_content(modules: list[str]) -> str:
    grouped: dict[str, list[str]] = defaultdict(list)
    for mod in modules:
        parts = mod.split(".")
        key = parts[1] if len(parts) > 1 else "misc"
        grouped[key].append(mod)

    order = ["device", "env", "limits", "tools", "misc"]
    lines: list[str] = [
        "API Modules",
        "===========",
        "",
        "This page is generated from ``src/mpylab``.",
        "",
    ]
    for key in order:
        mods = grouped.get(key, [])
        if not mods:
            continue
        heading = f"mpylab.{key}" if key != "misc" else "misc"
        lines.extend([heading, "=" * len(heading), ""])
        for mod in mods:
            title = make_title(mod)
            lines.extend(
                [
                    title,
                    section_underline(title),
                    "",
                    f".. automodule:: {mod}",
                    "   :members:",
                    "   :undoc-members:",
                    "   :inherited-members:",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    src_root = repo_root / "src" / "mpylab"
    out_file = repo_root / "docs" / "source" / "api" / "modules.rst"
    out_file.parent.mkdir(parents=True, exist_ok=True)
    modules = discover_modules(src_root)
    out_file.write_text(build_content(modules), encoding="utf-8")
    print(f"Generated {out_file} with {len(modules)} modules.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
