#!/usr/bin/env python3
"""Audit Sphinx module coverage and public API docstring coverage.

Checks:
- documented automodule entries that do not exist in source tree
- source modules that are not referenced by any automodule directive
- missing docstrings on public API symbols
- missing ``-de``/``-en`` page counterparts in docs
- potentially non-English public API docstrings (heuristic)

Public API policy used by this audit:
- public modules: all importable ``*.py`` under ``src/mpylab`` except
  ``__init__.py`` and modules below ``legacy``
- public classes/functions: top-level names that do not start with ``_``
- public methods: methods on public classes that do not start with ``_``
"""

from __future__ import annotations

import argparse
import ast
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

AUTOMODULE_RE = re.compile(r"^\s*\.\.\s+automodule::\s+([A-Za-z0-9_\.]+)\s*$")
DOCS_EXCLUDE_MODULES = {
    # Generated by yapps2 from dot.g; documented via dedicated grammar page.
    "mpylab.tools.dot",
}
DOCSTRING_EXCLUDE_MODULES = {
    # Generated by yapps2 from dot.g; do not edit docstrings in generated code.
    "mpylab.tools.dot",
}
QT_EVENT_METHOD_NAMES = {
    "actionEvent",
    "changeEvent",
    "childEvent",
    "closeEvent",
    "contextMenuEvent",
    "customEvent",
    "dragEnterEvent",
    "dragLeaveEvent",
    "dragMoveEvent",
    "dropEvent",
    "enterEvent",
    "event",
    "eventFilter",
    "focusInEvent",
    "focusOutEvent",
    "hideEvent",
    "inputMethodEvent",
    "keyPressEvent",
    "keyReleaseEvent",
    "leaveEvent",
    "mouseDoubleClickEvent",
    "mouseMoveEvent",
    "mousePressEvent",
    "mouseReleaseEvent",
    "moveEvent",
    "paintEvent",
    "resizeEvent",
    "showEvent",
    "tabletEvent",
    "timerEvent",
    "wheelEvent",
}
LANG_SUFFIX_RE = re.compile(r"^(?P<base>.+)-(?P<lang>de|en)\.rst$")
LANG_TRAILING_SUFFIX_RE = re.compile(r"-(de|en)\.rst$")
GERMAN_WORD_RE = re.compile(
    r"\b("
    r"der|die|das|und|mit|nicht|wird|werden|kann|soll|"
    r"beispiel|verwendung|hinweis|klasse|gerät|treiber|"
    r"messung|rueckgabe|rückgabe|beschreibung"
    r")\b",
    re.IGNORECASE,
)
GERMAN_CHAR_RE = re.compile(r"[äöüßÄÖÜ]")


def is_valid_module_path(parts: list[str]) -> bool:
    """Return whether every module path component is a valid identifier."""
    return all(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", p) is not None for p in parts)


def is_public_method_name(name: str) -> bool:
    """Return whether a class method name is considered public API."""
    if name.startswith("_"):
        return False
    return name not in QT_EVENT_METHOD_NAMES


@dataclass(frozen=True)
class SymbolDoc:
    """Docstring status for one public API symbol."""

    file: Path
    package: str
    kind: str
    symbol: str
    has_docstring: bool
    docstring: str | None


@dataclass(frozen=True)
class DocstringLanguageIssue:
    """Heuristic language issue found in a public API docstring."""

    file: Path
    symbol: str
    kind: str
    score: int
    preview: str


def discover_source_modules(src_root: Path) -> dict[str, Path]:
    """Discover importable source modules and map module name to file path."""
    module_to_file: dict[str, Path] = {}
    for pyf in src_root.rglob("*.py"):
        if "__pycache__" in pyf.parts or pyf.name == "__init__.py":
            continue
        rel = pyf.relative_to(src_root).with_suffix("")
        parts = list(rel.parts)
        if not is_valid_module_path(parts):
            continue
        mod = ".".join(["mpylab"] + parts)
        if ".legacy." in mod:
            continue
        if mod in DOCS_EXCLUDE_MODULES:
            continue
        module_to_file[mod] = pyf
    return module_to_file


def discover_documented_modules(docs_root: Path) -> set[str]:
    """Discover all modules referenced by Sphinx ``automodule`` directives."""
    documented: set[str] = set()
    for rst in docs_root.rglob("*.rst"):
        text = rst.read_text(encoding="utf-8")
        for line in text.splitlines():
            m = AUTOMODULE_RE.match(line)
            if m:
                documented.add(m.group(1))
    return documented


def discover_public_api_symbols(source_modules: dict[str, Path]) -> tuple[list[SymbolDoc], list[tuple[Path, str]]]:
    """Collect public symbols and their docstring status based on the audit policy."""
    symbols: list[SymbolDoc] = []
    parse_errors: list[tuple[Path, str]] = []
    for module_name, pyf in sorted(source_modules.items()):
        if module_name in DOCSTRING_EXCLUDE_MODULES:
            continue
        package = module_name.split(".")[1] if "." in module_name else "misc"
        try:
            tree = ast.parse(pyf.read_text(encoding="utf-8"))
        except SyntaxError as exc:
            parse_errors.append((pyf, f"{exc.msg} (line {exc.lineno})"))
            continue

        symbols.append(
            SymbolDoc(
                file=pyf,
                package=package,
                kind="module",
                symbol=module_name,
                has_docstring=ast.get_docstring(tree) is not None,
                docstring=ast.get_docstring(tree),
            )
        )

        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.name.startswith("_"):
                    continue
                symbols.append(
                    SymbolDoc(
                        file=pyf,
                        package=package,
                        kind="function",
                        symbol=f"{module_name}.{node.name}",
                        has_docstring=ast.get_docstring(node) is not None,
                        docstring=ast.get_docstring(node),
                    )
                )
            elif isinstance(node, ast.ClassDef):
                if node.name.startswith("_"):
                    continue
                class_name = f"{module_name}.{node.name}"
                symbols.append(
                    SymbolDoc(
                        file=pyf,
                        package=package,
                        kind="class",
                        symbol=class_name,
                        has_docstring=ast.get_docstring(node) is not None,
                        docstring=ast.get_docstring(node),
                    )
                )
                for member in node.body:
                    if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        if not is_public_method_name(member.name):
                            continue
                        symbols.append(
                            SymbolDoc(
                                file=pyf,
                                package=package,
                                kind="method",
                                symbol=f"{class_name}.{member.name}",
                                has_docstring=ast.get_docstring(member) is not None,
                                docstring=ast.get_docstring(member),
                            )
                        )
    return symbols, parse_errors


def discover_language_counterpart_gaps(docs_root: Path) -> tuple[list[str], list[str]]:
    """Return missing language counterparts for suffix and ``de/``/``en/`` layouts."""
    suffix_variants: dict[str, set[str]] = {}
    dir_variants: dict[str, set[str]] = {}
    for rst in docs_root.rglob("*.rst"):
        rel = rst.relative_to(docs_root).as_posix()
        if rel.startswith("de/"):
            dir_variants.setdefault(rel[3:], set()).add("de")
        elif rel.startswith("en/"):
            dir_variants.setdefault(rel[3:], set()).add("en")
        match = LANG_SUFFIX_RE.match(rel)
        if not match:
            continue
        base = match.group("base")
        lang = match.group("lang")
        suffix_variants.setdefault(base, set()).add(lang)

    missing_de: set[str] = set()
    missing_en: set[str] = set()
    for rel, langs in sorted(dir_variants.items()):
        if "de" in langs and "en" not in langs:
            missing_en.add(f"en/{rel}")
        if "en" in langs and "de" not in langs:
            missing_de.add(f"de/{rel}")

    for base, langs in sorted(suffix_variants.items()):
        if "de" in langs and "en" not in langs:
            missing_en.add(f"{base}-en.rst")
        if "en" in langs and "de" not in langs:
            missing_de.add(f"{base}-de.rst")
    return sorted(missing_de), sorted(missing_en)


def find_non_english_docstrings(symbols: list[SymbolDoc]) -> list[DocstringLanguageIssue]:
    """Heuristically detect potentially non-English public API docstrings."""
    issues: list[DocstringLanguageIssue] = []
    for sym in symbols:
        if not sym.docstring:
            continue
        text = sym.docstring.strip()
        if not text:
            continue

        score = len(set(m.group(0).lower() for m in GERMAN_WORD_RE.finditer(text)))
        if GERMAN_CHAR_RE.search(text):
            score += 1
        if score < 2:
            continue

        preview = text.splitlines()[0].strip()
        issues.append(
            DocstringLanguageIssue(
                file=sym.file,
                symbol=sym.symbol,
                kind=sym.kind,
                score=score,
                preview=preview[:120],
            )
        )
    return sorted(issues, key=lambda item: (-item.score, item.symbol))


def read_toctree_entries(index_file: Path) -> list[str]:
    """Read explicit ``.rst`` entries from a Sphinx index-like file."""
    entries: list[str] = []
    for line in index_file.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(".. ") or stripped.startswith(":"):
            continue
        if stripped.endswith(".rst"):
            entries.append(stripped)
    return entries


def normalize_lang_entry(entry: str) -> str:
    """Normalize ``-de``/``-en`` suffixes so EN and DE toctrees can be compared."""
    normalized = entry.strip()
    if normalized.startswith("../"):
        normalized = normalized[3:]
    normalized = re.sub(r"^(de|en)/", "", normalized)
    return LANG_TRAILING_SUFFIX_RE.sub(".rst", normalized)


def discover_toctree_order_mismatches(docs_root: Path) -> list[str]:
    """Compare normalized EN and DE index toctree order and report mismatches."""
    de_index = docs_root / "de" / "index.rst"
    en_index = docs_root / "en" / "index.rst"
    mismatches: list[str] = []
    if not de_index.exists():
        mismatches.append(f"Missing file: {de_index}")
        return mismatches
    if not en_index.exists():
        mismatches.append(f"Missing file: {en_index}")
        return mismatches

    de_entries = read_toctree_entries(de_index)
    en_entries = read_toctree_entries(en_index)
    de_norm = [normalize_lang_entry(e) for e in de_entries]
    en_norm = [normalize_lang_entry(e) for e in en_entries]

    if de_norm == en_norm:
        return mismatches

    if len(de_norm) != len(en_norm):
        mismatches.append(f"Different entry count: de={len(de_norm)} vs en={len(en_norm)}")

    max_len = max(len(de_norm), len(en_norm))
    for idx in range(max_len):
        de_val = de_norm[idx] if idx < len(de_norm) else "<missing>"
        en_val = en_norm[idx] if idx < len(en_norm) else "<missing>"
        if de_val != en_val:
            mismatches.append(f"Position {idx + 1}: de={de_val} vs en={en_val}")
    return mismatches


def count_by_kind(symbols: Iterable[SymbolDoc]) -> dict[str, int]:
    """Count symbols per symbol kind."""
    counts = {"module": 0, "class": 0, "function": 0, "method": 0}
    for sym in symbols:
        counts[sym.kind] += 1
    return counts


def print_docstring_report(symbols: list[SymbolDoc], top_missing: int) -> None:
    """Print docstring coverage summary and hotspots."""
    total_by_kind = count_by_kind(symbols)
    missing = [sym for sym in symbols if not sym.has_docstring]
    missing_by_kind = count_by_kind(missing)

    print("Docstring policy: public top-level classes/functions and public class methods.")
    if DOCSTRING_EXCLUDE_MODULES:
        print(
            "Docstring exclusions: "
            + ", ".join(sorted(DOCSTRING_EXCLUDE_MODULES))
        )
    if DOCS_EXCLUDE_MODULES:
        print("Docs coverage exclusions: " + ", ".join(sorted(DOCS_EXCLUDE_MODULES)))
    print(f"Public API symbols: {len(symbols)}")
    print(
        "Missing docstrings: "
        f"{len(missing)} "
        f"(module={missing_by_kind['module']}, "
        f"class={missing_by_kind['class']}, "
        f"function={missing_by_kind['function']}, "
        f"method={missing_by_kind['method']})"
    )
    print(
        "Coverage by kind: "
        f"module={total_by_kind['module'] - missing_by_kind['module']}/{total_by_kind['module']}, "
        f"class={total_by_kind['class'] - missing_by_kind['class']}/{total_by_kind['class']}, "
        f"function={total_by_kind['function'] - missing_by_kind['function']}/{total_by_kind['function']}, "
        f"method={total_by_kind['method'] - missing_by_kind['method']}/{total_by_kind['method']}"
    )

    if not missing:
        return

    by_package: dict[str, int] = {}
    by_file: dict[Path, int] = {}
    for sym in missing:
        by_package[sym.package] = by_package.get(sym.package, 0) + 1
        by_file[sym.file] = by_file.get(sym.file, 0) + 1

    print("Missing by package:")
    for package, count in sorted(by_package.items(), key=lambda item: (-item[1], item[0])):
        print(f"  - {package}: {count}")

    print(f"Top {top_missing} files with missing docstrings:")
    for file_path, count in sorted(by_file.items(), key=lambda item: (-item[1], str(item[0])))[:top_missing]:
        print(f"  - {file_path}: {count}")


def print_language_counterpart_report(missing_de: list[str], missing_en: list[str]) -> None:
    """Print report for missing ``-de``/``-en`` docs page counterparts."""
    total = len(missing_de) + len(missing_en)
    print(f"Missing language counterparts: {total}")
    if missing_de:
        print("Missing German counterparts (-de):")
        for rel in missing_de:
            print(f"  - {rel}")
    if missing_en:
        print("Missing English counterparts (-en):")
        for rel in missing_en:
            print(f"  - {rel}")


def print_docstring_language_report(issues: list[DocstringLanguageIssue], top_issues: int) -> None:
    """Print report for potentially non-English public API docstrings."""
    print(f"Potentially non-English public API docstrings: {len(issues)}")
    if not issues:
        return
    print(f"Top {top_issues} potential language issues:")
    for issue in issues[:top_issues]:
        print(
            f"  - {issue.symbol} [{issue.kind}] "
            f"(score={issue.score}, file={issue.file}): {issue.preview}"
        )


def print_toctree_order_report(mismatches: list[str]) -> None:
    """Print report for EN/DE index toctree order mismatches."""
    print(f"DE/EN toctree order mismatches: {len(mismatches)}")
    if not mismatches:
        return
    for item in mismatches:
        print(f"  - {item}")


def main() -> int:
    """Run the documentation/API coverage audits."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src-root", default="src/mpylab", help="Path to source tree (default: src/mpylab)")
    parser.add_argument("--docs-root", default="docs/source", help="Path to docs tree (default: docs/source)")
    parser.add_argument(
        "--fail-on-uncovered",
        action="store_true",
        help="Return non-zero if source modules are not covered by automodule entries",
    )
    parser.add_argument(
        "--fail-on-missing-docstrings",
        action="store_true",
        help="Return non-zero if public API symbols are missing docstrings",
    )
    parser.add_argument(
        "--top-missing-files",
        type=int,
        default=20,
        help="How many files to include in the missing-docstring hotspot list (default: 20)",
    )
    parser.add_argument(
        "--top-language-issues",
        type=int,
        default=20,
        help="How many suspected non-English docstring issues to print (default: 20)",
    )
    parser.add_argument(
        "--fail-on-missing-language-counterparts",
        action="store_true",
        help="Return non-zero if any -de/-en counterpart page is missing",
    )
    parser.add_argument(
        "--fail-on-non-english-docstrings",
        action="store_true",
        help="Return non-zero if heuristic detects potentially non-English public API docstrings",
    )
    parser.add_argument(
        "--fail-on-toctree-order-mismatch",
        action="store_true",
        help="Return non-zero if normalized EN and DE index toctree order differ",
    )
    args = parser.parse_args()

    src_root = Path(args.src_root)
    docs_root = Path(args.docs_root)

    source_modules = discover_source_modules(src_root)
    documented_modules = discover_documented_modules(docs_root)
    public_symbols, parse_errors = discover_public_api_symbols(source_modules)

    stale_documented = sorted(m for m in documented_modules if m not in source_modules)
    uncovered_source = sorted(m for m in source_modules if m not in documented_modules)
    missing_docstrings = [sym for sym in public_symbols if not sym.has_docstring]
    missing_de_pages, missing_en_pages = discover_language_counterpart_gaps(docs_root)
    non_english_docstrings = find_non_english_docstrings(public_symbols)
    toctree_order_mismatches = discover_toctree_order_mismatches(docs_root)

    print(f"Source modules: {len(source_modules)}")
    print(f"Documented automodule entries: {len(documented_modules)}")
    print(f"Stale documented modules: {len(stale_documented)}")
    if stale_documented:
        for m in stale_documented:
            print(f"  - {m}")
    print(f"Uncovered source modules: {len(uncovered_source)}")
    if uncovered_source:
        preview = uncovered_source[:100]
        for m in preview:
            print(f"  - {m}")
        if len(uncovered_source) > len(preview):
            print(f"  ... and {len(uncovered_source) - len(preview)} more")
    if parse_errors:
        print(f"Modules skipped due to parse errors: {len(parse_errors)}")
        for path, error in parse_errors:
            print(f"  - {path}: {error}")

    print_docstring_report(public_symbols, top_missing=args.top_missing_files)
    print_language_counterpart_report(missing_de_pages, missing_en_pages)
    print_docstring_language_report(non_english_docstrings, top_issues=args.top_language_issues)
    print_toctree_order_report(toctree_order_mismatches)

    if stale_documented:
        return 1
    if args.fail_on_uncovered and uncovered_source:
        return 2
    if args.fail_on_missing_docstrings and missing_docstrings:
        return 3
    if args.fail_on_missing_language_counterparts and (missing_de_pages or missing_en_pages):
        return 4
    if args.fail_on_non_english_docstrings and non_english_docstrings:
        return 5
    if args.fail_on_toctree_order_mismatch and toctree_order_mismatches:
        return 6
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
